[project]
name = "prisma-client-python-json-study"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "prisma>=0.15.0",
]
