[project]
name = "prisma-client-python-json-study"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "prisma (>=0.15.0,<0.16.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
